package corpbi;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PolizasRoble", targetNamespace = "CorpBI", wsdlLocation = "conf/wsdl/PolizasRobleMock.wsdl")
public class PolizasRoble_Service extends Service{

    private final static URL POLIZASROBLE_WSDL_LOCATION;
    private final static WebServiceException POLIZASROBLE_EXCEPTION;
    private final static QName POLIZASROBLE_QNAME = new QName("CorpBI", "PolizasRoble");

    static {
    	POLIZASROBLE_WSDL_LOCATION = corpbi.PolizasRoble_Service.class.getResource("PolizasRoble.wsdl");
        WebServiceException e = null;
        if (POLIZASROBLE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'PolizasRoble.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        POLIZASROBLE_EXCEPTION = e;
    }

    public PolizasRoble_Service() {
        super(__getWsdlLocation(), POLIZASROBLE_QNAME);
    }

    public PolizasRoble_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), POLIZASROBLE_QNAME, features);
    }

    public PolizasRoble_Service(URL wsdlLocation) {
        super(wsdlLocation, POLIZASROBLE_QNAME);
    }

    public PolizasRoble_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, POLIZASROBLE_QNAME, features);
    }

    public PolizasRoble_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PolizasRoble_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns PolizasRoble
     */
    @WebEndpoint(name = "PolizasRobleSOAP")
    public PolizasRoble getPolizasRobleSOAP() {
        return super.getPort(new QName("CorpBI", "PolizasRobleSOAP"), PolizasRoble.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PolizasRoble
     */
    @WebEndpoint(name = "PolizasRobleSOAP")
    public PolizasRoble getPolizasRobleSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("CorpBI", "PolizasRobleSOAP"), PolizasRoble.class, features);
    }

    private static URL __getWsdlLocation() {
        if (POLIZASROBLE_EXCEPTION!= null) {
            throw POLIZASROBLE_EXCEPTION;
        }
        return POLIZASROBLE_WSDL_LOCATION;
    }

}
